# Rubyベース
FROM ruby:3.3.6

# 文字コード & タイムゾーン設定
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# Node.js & Yarnの導入（RailsがJSやCSS処理するために必要）
RUN apt-get update -qq \
&& apt-get install -y ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
&& NODE_MAJOR=20 \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
&& wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# パッケージインストール（PostgreSQL関連は削除済）
RUN apt-get update -qq && apt-get install -y build-essential nodejs yarn vim

# 作業用ディレクトリ作成
RUN mkdir /myapp
WORKDIR /myapp

# bundlerインストール（gem管理）
RUN gem install bundler

# ローカルのコードをコンテナにコピー
COPY . /myapp
